import Head from 'next/head';
import React from 'react';
import Header from './header';
import Search from './search';
import Tabar from './tabar';

const Lajoutmanager = (props) => {
    return (
        <div className="bg-gray-50">
            <Head>
            <title>{props?.title}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/rlogo.svg" />
            </Head>
    
            {/* header page*/}
            <Header />
            
            <main className="h-full pb-12 md:pb-0">
            
                {props.children}
    
            </main>
            
            <Tabar />  
        </div>
    );
}

export default Lajoutmanager;
